version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - npm install
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 417901114174.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - docker -version
      - docker build -t weather .
      - echo Compiling the Node.js code
  post_build:
    commands:
      - docker tag weather:latest 417901114174.dkr.ecr.ap-southeast-1.amazonaws.com/weather:latest
      - docker push 417901114174.dkr.ecr.ap-southeast-1.amazonaws.com/weather:latest
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
