version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - npm install
  pre_build:
    commands:
      - docker -v
  build:
    commands:
      - docker build -t weather-app .
      - echo Compiling the Node.js code
  post_build:
    commands:
      - docker tag weather-app rathijaat001/weather-app
      - docker push rathijaat001/weather-app
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
